=== Tom-Lemmens/XmlStructTools.jl/XmlStructWriter.jl/test/test_data/generic_cases/type_in_type.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:TestTypeInType="TestTypeInType" targetNamespace="TestTypeInType">

    <element name="document" type="TestTypeInType:documentType"/>

    <simpleType name="TestSimpleType1">
        <annotation>
            <documentation>An example of a simple xsd type.</documentation>
        </annotation>
        <restriction base="string">
            <maxLength value="4"/>
            <pattern value="([0-9A-Z]{4})?"/>
        </restriction>
    </simpleType>

    <complexType name="TestComplexType1">
        <annotation>
            <documentation>Example of a complex XSD type that uses types defined under it's elements.</documentation>
        </annotation>
        <sequence>
            <element name="A">
                <complexType>
                    <annotation>
                        <documentation>An example of a complex xsd type.</documentation>
                    </annotation>
                    <sequence>
                        <element name="Element_string" type="string"/>
                        <element name="Element_double" type="double"/>
                        <element name="Element_boolean" type="boolean"/>
                        <element name="Element_dateTime" type="dateTime"/>
                    </sequence>
                </complexType>
            </element>
            <element name="B">
                <complexType>
                    <annotation>
                        <documentation>An example of an extended simple xsd type.</documentation>
                    </annotation>
                    <simpleContent>
                        <extension base="TestTypeInType:TestSimpleType1">
                            <attribute name="extended_b" fixed="b"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
            <element name="C">
                <complexType>
                    <annotation>
                        <documentation>An example of a complex xsd type.</documentation>
                    </annotation>
                    <sequence>
                        <element name="Element_string" type="string"/>
                        <element name="Element_double" type="double"/>
                        <element name="Element_boolean" type="boolean"/>
                        <element name="Element_dateTime" type="dateTime"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="TestComplexType2">
        <annotation>
            <documentation>Example of a complex XSD type that uses types defined under it's elements and depends on a type defined later in the xsd.</documentation>
        </annotation>
        <sequence>
            <element name="A">
                <complexType>
                    <annotation>
                        <documentation>An example of an extended simple xsd type.</documentation>
                    </annotation>
                    <simpleContent>
                        <extension base="TestTypeInType:TestSimpleType1">
                            <attribute name="extended_b" fixed="b"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
            <element name="B">
                <complexType>
                    <annotation>
                        <documentation>An example of an extended simple xsd type.</documentation>
                    </annotation>
                    <simpleContent>
                        <extension base="TestTypeInType:TestSimpleType2">
                            <attribute name="extended_b" fixed="b"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <simpleType name="TestSimpleType2">
        <annotation>
            <documentation>An example of a simple xsd type.</documentation>
        </annotation>
        <restriction base="string">
            <maxLength value="4"/>
            <pattern value="([0-9A-Z]{4})?"/>
        </restriction>
    </simpleType>

    <complexType name="TestComplexType3">
        <annotation>
            <documentation>Example of a complex XSD type that uses a mix of types defined under it's elements and normal types in a particular order.</documentation>
        </annotation>
        <sequence>
            <element name="A">
                <complexType>
                    <annotation>
                        <documentation>An example of an extended simple xsd type.</documentation>
                    </annotation>
                    <simpleContent>
                        <extension base="TestTypeInType:TestSimpleType1">
                            <attribute name="extended_b" fixed="b"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
            <element name="S1" type="TestTypeInType:TestSimpleType2"/>
            <element name="B">
                <complexType>
                    <annotation>
                        <documentation>An example of an extended simple xsd type.</documentation>
                    </annotation>
                    <simpleContent>
                        <extension base="TestTypeInType:TestSimpleType2">
                            <attribute name="extended_b" fixed="b"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
            <element name="S2" type="TestTypeInType:TestSimpleType2"/>
        </sequence>
    </complexType>

    <complexType name="documentType">
        <sequence>
            <element name="TestElement1" type="TestTypeInType:TestComplexType1"/>
            <element name="TestElement2" type="TestTypeInType:TestComplexType2"/>
            <element name="TestElement3" type="TestTypeInType:TestComplexType3"/>
        </sequence>
    </complexType>

</schema>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructWriter.jl/test/test_data/generic_cases/type_in_type.xml
<?xml version="1.0" encoding="UTF-8"?>
<TestTypeInType:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestTypeInType type_in_type.xsd" xmlns:TestTypeInType="TestTypeInType">
    <TestElement1>
        <A>
            <Element_string>oo</Element_string>
            <Element_double>1578.659</Element_double>
            <Element_boolean>false</Element_boolean>
            <Element_dateTime>2022-05-10T10:22:49.152+01:00</Element_dateTime>
        </A>
        <B extended_b="b">CCCC</B>
        <C>
            <Element_string>eyggi</Element_string>
            <Element_double>5457.48789</Element_double>
            <Element_boolean>true</Element_boolean>
            <Element_dateTime>2022-05-10T10:22:49Z</Element_dateTime>
        </C>
    </TestElement1>
    <TestElement2>
        <A>AAAA</A>
        <B>BBBB</B>
    </TestElement2>
    <TestElement3>
        <A>A9A9</A>
        <S1>B44B</S1>
        <B>2D7D</B>
        <S2>FGHK</S2>
    </TestElement3>
</TestTypeInType:document>
