=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/basic_types.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:TestComplexAndSimple="TestComplexAndSimple" targetNamespace="TestComplexAndSimple">

<element name="document" type="TestComplexAndSimple:documentType"/>

<complexType name="TestComplexType1">
    <annotation>
        <documentation>An example of a complex xsd type.</documentation>
    </annotation>
    <sequence>
        <element name="Element_string" type="string"/>
        <element name="Element_double" type="double"/>
        <element name="Element_boolean" type="boolean"/>
        <element name="Element_decimal" type="decimal"/>
        <element name="Element_dateTime" type="dateTime"/>
        <element name="Element_integer" type="integer"/>
        <element name="Element_nonNegativeInteger" type="nonNegativeInteger"/>
        <element name="Element_positiveInteger" type="positiveInteger"/>
    </sequence>
</complexType>

<complexType name="TestComplexType6">
    <annotation>
        <documentation>An example of a complex xsd type.</documentation>
    </annotation>
    <sequence>
        <element name="Element_string" type="string"/>
        <element name="Element_double" type="double"/>    
        <element name="Element_dateTime" type="dateTime"/>
    </sequence>
</complexType>

<simpleType name="TestSimpleType1">
    <annotation>
        <documentation>An example of a simple xsd type.</documentation>
    </annotation>
    <restriction base="string">
        <maxLength value="4"/>
        <pattern value="([0-9A-Z]{4})?"/>
    </restriction>
</simpleType>

<complexType name="documentType">
    <sequence>
        <element name="TestElement1" type="TestComplexAndSimple:TestComplexType1"/>
        <element name="TestElement2" type="TestComplexAndSimple:TestSimpleType1"/>
         <element name="TestElement3" type="TestComplexAndSimple:TestComplexType6"/>
    </sequence>
</complexType>

</schema>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructWriter.jl/test/test_data/generic_cases/basic_types.xml
<?xml version="1.0" encoding="utf-8"?>

<TestComplexAndSimple:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestComplexAndSimple basic_types.xsd" xmlns:TestComplexAndSimple="TestComplexAndSimple">
    <TestElement1>
        <Element_string>aaaa</Element_string>
        <Element_double>100.22</Element_double>
        <Element_boolean>true</Element_boolean>
        <Element_decimal>5.55</Element_decimal>
        <Element_dateTime>2022-05-10T10:22:49.152+01:00</Element_dateTime>
        <Element_integer>-778</Element_integer>
        <Element_nonNegativeInteger>0</Element_nonNegativeInteger>
        <Element_positiveInteger>663</Element_positiveInteger>
    </TestElement1>

    <TestElement2>99A9</TestElement2>

    <TestElement3>
        <Element_string>bbbb</Element_string>
        <Element_double>464.558</Element_double>
        <Element_dateTime>2002-10-10T10:22:49.152-02:00</Element_dateTime>
    </TestElement3>
</TestComplexAndSimple:document>
