=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/complex_content.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:TestComplexContent="TestComplexContent" targetNamespace="TestComplexContent">

<element name="document" type="TestComplexContent:documentType"/>

<simpleType name="SimpleType1">
    <restriction base="decimal"/>
</simpleType>

<complexType name="TestComplexType1">
    <annotation>
        <documentation>An example of a complex xsd type.</documentation>
    </annotation>
    <sequence>
        <element name="Element_string" type="string"/>
        <element name="Element_double" type="double"/>
        <element name="Element_boolean" type="boolean"/>
        <element name="Element_decimal" type="decimal"/>
        <element name="Element_dateTime" type="dateTime"/>
        <element name="Element_integer" type="integer"/>
        <element name="Element_nonNegativeInteger" type="nonNegativeInteger"/>
        <element name="Element_positiveInteger" type="positiveInteger"/>
        <element name="Element_empty" minOccurs="0">
            <annotation>
                <documentation xml:lang="en">An example of an empty type.</documentation>
            </annotation>
            <complexType/>
        </element>
    </sequence>
</complexType>

<complexType name="TestComplexType2">
    <annotation>
        <documentation>An example of a complex xsd type with complex content.</documentation>
    </annotation>
    <complexContent>
        <extension base="TestComplexContent:TestComplexType1">
            <sequence>
                <element name="Element_integer_ext" type="integer"/>
                <element name="Element_boolean_ext" type="boolean"/>
            </sequence>
        </extension>
    </complexContent>
</complexType>

<complexType name="TestComplexType3">
    <annotation>
        <documentation>An example of a complex xsd type with complex content.</documentation>
    </annotation>
    <complexContent>
        <extension base="TestComplexContent:TestComplexType1">
        </extension>
    </complexContent>
</complexType>

<complexType name="TestComplexType5">
	<complexContent>
		<extension base="TestComplexContent:TestComplexType4"/>
    </complexContent>
</complexType>

<complexType name="TestComplexType4">
	<sequence>
		<element name="simple1" default="0.0">
			<complexType>
			  <simpleContent>
				<extension base="TestComplexContent:SimpleType1">
				  <attribute name="unit" fixed="s"/>
				</extension>
			  </simpleContent>
			</complexType>
      </element>
	</sequence>
</complexType>

<complexType name="documentType">
    <sequence>
        <element name="TestElement2" type="TestComplexContent:TestComplexType2"/>
        <element name="TestElement3" type="TestComplexContent:TestComplexType3"/>
        <element name="TestElement5" type="TestComplexContent:TestComplexType5"/>
    </sequence>
</complexType>

</schema>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/complex_content.xml
<?xml version="1.0" encoding="utf-8"?>

<TestComplexContent:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestComplexContent complex_content.xsd" xmlns:TestComplexContent="TestComplexContent">
    <TestElement2>
        <Element_string>aaaa</Element_string>
        <Element_double>100.22</Element_double>
        <Element_boolean>true</Element_boolean>
        <Element_decimal>5.55</Element_decimal>
        <Element_dateTime>2022-05-10T10:22:49.152+01:00</Element_dateTime>
        <Element_integer>-778</Element_integer>
        <Element_nonNegativeInteger>0</Element_nonNegativeInteger>
        <Element_positiveInteger>663</Element_positiveInteger>
        <Element_integer_ext>-78</Element_integer_ext>
        <Element_boolean_ext>false</Element_boolean_ext>
    </TestElement2>
    <TestElement3>
        <Element_string>bbbb</Element_string>
        <Element_double>55.22</Element_double>
        <Element_boolean>false</Element_boolean>
        <Element_decimal>57.55</Element_decimal>
        <Element_dateTime>2022-05-15T10:22:49.152+01:00</Element_dateTime>
        <Element_integer>1004</Element_integer>
        <Element_nonNegativeInteger>10</Element_nonNegativeInteger>
        <Element_positiveInteger>4</Element_positiveInteger>
    </TestElement3>
    <TestElement5>
        <simple1>5.5</simple1>
    </TestElement5>
</TestComplexContent:document>
