=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/date_formats.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:TestDateFormats="TestDateFormats" targetNamespace="TestDateFormats">

<element name="document" type="TestDateFormats:documentType"/>

<complexType name="TestComplexType1">
    <annotation>
        <documentation>An example of a complex xsd type with a vector of date times.</documentation>
    </annotation>
    <sequence>
        <element name="Element_dateTime" type="dateTime" maxOccurs="unbounded"/>
    </sequence>
</complexType>

<complexType name="documentType">
    <sequence>
        <element name="TestElement1" type="TestDateFormats:TestComplexType1"/>
    </sequence>
</complexType>

</schema>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/date_formats.xml
<?xml version="1.0" encoding="utf-8"?>

<TestDateFormats:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestDateFormats date_formats.xsd" xmlns:TestDateFormats="TestDateFormats">
    <TestElement1>
        <Element_dateTime>2022-05-10T10:22:49.152+01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.152-01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.152Z</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.152</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.152555</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.15255</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1525575</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1+01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1-01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1Z</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49+01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49-01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49Z</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1525575+01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1525575-01:00</Element_dateTime>
        <Element_dateTime>2022-05-10T10:22:49.1525575Z</Element_dateTime>
    </TestElement1>

</TestDateFormats:document>
