=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/optional_elements.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:OptionalElements="OptionalElements" targetNamespace="OptionalElements">

<element name="document" type="OptionalElements:documentType"/>

<complexType name="TestComplexType1">
    <annotation>
        <documentation>An example of a complex xsd type with an optional element without default value.</documentation>
    </annotation>
    <sequence>
        <element name="Element_string" type="string" minOccurs="0"/>
        <element name="Element_double" type="double"/>
        <element name="Element_simple1" type="OptionalElements:TestSimpleType1" minOccurs="0"/>
        <element name="Element_simple2" type="OptionalElements:TestSimpleType2" minOccurs="0"/>
    </sequence>
</complexType>

<complexType name="TestComplexType2">
    <annotation>
        <documentation>An example of a complex xsd type with an optional elements with default values.</documentation>
    </annotation>
    <sequence>
        <element name="Element_string" type="string" default="aaa"/>
        <element name="Element_double" type="double" default="55.2"/>
        <element name="Element_simple1" type="OptionalElements:TestSimpleType1" minOccurs="0" default="0"/>
        <element name="Element_simple2" type="OptionalElements:TestSimpleType2" minOccurs="0" default="AAAA"/>
    </sequence>
</complexType>

<complexType name="TestComplexType3">
    <annotation>
        <documentation>An example of a complex xsd type with vector optional elements and default values.</documentation>
    </annotation>
    <sequence>
        <element name="Element_simple1" type="OptionalElements:TestSimpleType1" minOccurs="0" maxOccurs="unbounded" default="0"/>
        <element name="Element_simple2" type="OptionalElements:TestSimpleType2" minOccurs="0" maxOccurs="unbounded" default="AAAA"/>
        <element name="Element_simple2_or_nothing" type="OptionalElements:TestSimpleType2" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
</complexType>

<complexType name="TestComplexType4">
    <annotation>
        <documentation>An example of a complex xsd type with complex optional values.</documentation>
    </annotation>
    <sequence>
        <element name="Element_complex4" type="OptionalElements:TestComplexType4_element" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
</complexType>

<complexType name="TestComplexType4_element">
    <annotation>
        <documentation>An example of a complex xsd type with optional simple elements.</documentation>
    </annotation>
    <sequence>
        <element name="Element_simple1_1" type="OptionalElements:TestSimpleType1" minOccurs="0"/>
        <element name="Element_simple1_2" type="OptionalElements:TestSimpleType1" minOccurs="0" default="50"/>
        <element name="Element_simple2_1" type="OptionalElements:TestSimpleType2" minOccurs="0"/>
        <element name="Element_simple2_2" type="OptionalElements:TestSimpleType2" minOccurs="0" default="A4A4"/>
    </sequence>
</complexType>

<simpleType name="TestSimpleType1">
    <annotation>
        <documentation>An example of a simple xsd type.</documentation>
    </annotation>
    <restriction base="double">
        <maxInclusive value = "100"/>
    </restriction>
</simpleType>

<simpleType name="TestSimpleType2">
    <annotation>
        <documentation>An example of a simple xsd type.</documentation>
    </annotation>
    <restriction base="string">
        <maxLength value="4"/>
        <pattern value="([0-9A-Z]{4})?"/>
    </restriction>
</simpleType>

<complexType name="TestComplexType5">
    <annotation>
        <documentation>An example of a complex xsd type with an optional element with a type defined inside.</documentation>
    </annotation>
    <sequence>
        <element name="Element_simple1" minOccurs="0">
            <simpleType>
                <annotation>
                    <documentation>An example of a simple xsd type.</documentation>
                </annotation>
                <restriction base="string">
                    <maxLength value="10"/>
                </restriction>
            </simpleType>
        </element>
        <element name="Element_simple2" minOccurs="0" default="file.ext">
            <simpleType>
                <annotation>
                    <documentation>An example of a simple xsd type.</documentation>
                </annotation>
                <restriction base="string">
                    <maxLength value="10"/>
                </restriction>
            </simpleType>
        </element>
    </sequence>
</complexType>

<complexType name="TestComplexType6">
    <annotation>
        <documentation>An example of a complex xsd type with optional dateTime elements.</documentation>
    </annotation>
    <sequence>
        <element name="Element_simple1" type="dateTime" minOccurs="0" default="0001-01-01T00:00:00+00:00" />
        <element name="Element_simple2" type="dateTime" minOccurs="0"/>
        <element name="Element_simple3" type="dateTime" default="0001-02-03T04:05:06.666"/>
        <element name="Element_simple4" type="dateTime" minOccurs="0" default="0999-08-07T06:55:44-03:22" />
        <element name="Element_simple5" type="dateTime" minOccurs="0" default="0004-05-06T07:08:09Z" />
    </sequence>
</complexType>

<complexType name="documentType">
    <sequence>
        <element name="TestElement1" type="OptionalElements:TestComplexType1"/>
        <element name="TestElement2" type="OptionalElements:TestComplexType2"/>
        <element name="TestElement3" type="OptionalElements:TestComplexType3"/>
        <element name="TestElement4" type="OptionalElements:TestComplexType4"/>
        <element name="TestElement5" type="OptionalElements:TestComplexType5"/>
        <element name="TestElement6" type="OptionalElements:TestComplexType6"/>
    </sequence>
</complexType>

</schema>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructWriter.jl/test/test_data/generic_cases/optional_elements_1_expected.xml
<?xml version="1.0" encoding="utf-8"?>
<OptionalElements:document xsi:schemaLocation="OptionalElements optional_elements.xsd" xmlns:OptionalElements="OptionalElements" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <TestElement1>
    <Element_double>100.22</Element_double>
  </TestElement1>
  <TestElement2>
    <Element_string>aaa</Element_string>
    <Element_double>55.2</Element_double>
  </TestElement2>
  <TestElement3/>
  <TestElement4/>
  <TestElement5/>
  <TestElement6>
    <Element_simple3>0001-02-03T04:05:06.666</Element_simple3>
</TestElement6>
</OptionalElements:document>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/optional_elements_1.xml
<?xml version="1.0" encoding="utf-8"?>

<OptionalElements:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OptionalElements optional_elements.xsd" xmlns:OptionalElements="OptionalElements">
    <TestElement1>
        <Element_double>100.22</Element_double>
    </TestElement1>

    <TestElement2>
        <Element_string></Element_string>
        <Element_double></Element_double>
    </TestElement2>

    <TestElement3></TestElement3>

    <TestElement4>
        
    </TestElement4>
    <TestElement5></TestElement5>

    <TestElement6>
        <Element_simple3></Element_simple3>
    </TestElement6>
</OptionalElements:document>

=== Tom-Lemmens/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/generic_cases/optional_elements_2.xml
<?xml version="1.0" encoding="utf-8"?>

<OptionalElements:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="OptionalElements optional_elements.xsd" xmlns:OptionalElements="OptionalElements">
    <TestElement1>
        <Element_string>yuyuyuyu</Element_string>
        <Element_double>100.22</Element_double>
        <Element_simple1>10</Element_simple1>
        <Element_simple2>TTTT</Element_simple2>
    </TestElement1>

    <TestElement2>
        <Element_string>yiiiiiu</Element_string>
        <Element_double>550.22</Element_double>
        <Element_simple1>70</Element_simple1>
        <Element_simple2>YUYU</Element_simple2>
    </TestElement2>

    <TestElement3>
        <Element_simple1>70</Element_simple1>
        <Element_simple1>70</Element_simple1>
        <Element_simple1>78</Element_simple1>
        <Element_simple1>77</Element_simple1>
        <Element_simple2>YUII</Element_simple2>
        <Element_simple2_or_nothing>YUI1</Element_simple2_or_nothing>
        <Element_simple2_or_nothing>YUI2</Element_simple2_or_nothing>
        <Element_simple2_or_nothing>YUI3</Element_simple2_or_nothing>
    </TestElement3>

    <TestElement4>
        <Element_complex4>
            <Element_simple1_1>51</Element_simple1_1>
            <Element_simple1_2>14</Element_simple1_2>
            <Element_simple2_1>ERER</Element_simple2_1>
            <Element_simple2_2>UYUY</Element_simple2_2>
        </Element_complex4>
        <Element_complex4>
            <Element_simple1_1>74</Element_simple1_1>
            <Element_simple1_2>25</Element_simple1_2>
            <Element_simple2_1>U555</Element_simple2_1>
            <Element_simple2_2>A5A5</Element_simple2_2>
        </Element_complex4>
        <Element_complex4></Element_complex4>
    </TestElement4>

    <TestElement5>
        <Element_simple1>aaa</Element_simple1>
        <Element_simple2>"aaaaa"</Element_simple2>
    </TestElement5>

    <TestElement6>
        <Element_simple1></Element_simple1>
        <Element_simple2>2002-10-30T10:22:49-02:00</Element_simple2>
        <Element_simple3>0001-10-10T10:22:49.152</Element_simple3>
        <Element_simple4>2002-10-10T10:22:49.152Z</Element_simple4>
        <Element_simple5></Element_simple5>
    </TestElement6>
</OptionalElements:document>
